// pages/projects.vue
<template>
  <section class="repo-gallery">
  <h2>&lt;My GitHub Repositories/&gt;</h2>
  <div class="repo-grid">
    <div v-for="repo in repos" :key="repo.id" class="repo-card">
      <h3><a :href="repo.html_url" target="_blank">{{ repo.name }}</a></h3>
      <p>{{ repo.description || 'No description yet' }}</p>
      <span class="language">{{ repo.language || 'Unknown' }}</span>
      <span class="updated">Last updated: {{ new Date(repo.updated_at).toLocaleDateString() }}</span>
    </div>
  </div>
</section>
</template>

<script setup>
import {ref, onMounted } from 'vue'

const repos = ref([])

onMounted(async () => {
  try {
    const res = await fetch('https://api.github.com/users/S0FTS0RR0W/repos')
    const data = await res.json()
    repos.value = data.filter(repo => !repo.fork)
  } catch (err) {
    console.error('Failed to fetch repos:', err)
  }
})
</script>

<style scoped>
.repo-gallery {
  padding: 2rem;
  background: #0d1117;
  color: #c9d1d9;
  font-family: 'Fira Code', monospace;
}

.repo-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1.5rem;
}

.repo-card {
  background: #161b22;
  border: 1px solid #21262c;
  padding: 1rem;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(20, 20, 20, 0.1);
  transition: transform 0.2s ease;
}

.repo-card:hover {
  transform: translateY(-2px) scale(1.02);
  border-color: #238636;
}

.repo-card h3 a {
  color: #58a6ff;
  text-decoration: none;
}

.repo-card p {
  color: #8b949e;
  margin: 0.5rem 0;
}

.language, .updated {
  font-size: 0.8rem;
  color: #8b949e;
  display: block;
  margin-top: 0.25rem;
}
</style>

// app/projects/page.tsx
interface Repo {
  id: number;
  name: string;
  description: string | null;
  html_url: string;
}

//get GitHub repos
async function getRepos() {
  // TODO: Replace 'charlie' with your actual GitHub username
  const res = await fetch("https://api.github.com/users/S0FTS0RR0W/repos", {
    next: { revalidate: 3600 }, // Revalidate data once per hour
  });

  if (!res.ok) throw new Error("Failed to fetch projects");
  return res.json();
}

export default async function Projects() {
  const repos: Repo[] = await getRepos();

  return (
    <section className="font-mono flex flex-col items-center justify-center space-y-4">
      <h1>My Projects</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {repos.map((repo) => (
          <div key={repo.id} className="border p-4 rounded-lg">
            <h2 className="font-bold">{repo.name}</h2>
            <p>{repo.description}</p>
            <a
              href={repo.html_url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-teal-500 transition-all group inline-block"
            >
              View on GitHub
              <div className="bg-teal-500 h-0.5 w-0 group-hover:w-full transition-all duration-500"></div>
            </a>
          </div>
        ))}
      </div>
    </section>
  );
}
